### PR TITLE
Prototypical CHT values: use 2024 cert, not 2023, use Core v4.6, not v4.2

### PR DESCRIPTION
**Pull request by mrjones-plip**

### CODE REVIEW

**Comment by mrjones-plip** [comment]
@nydr - looking at what we tell people to [use for EKS](https://docs.communityhealthtoolkit.org/contribute/code/core/deploy-on-eks/#starting-and-stopping-aka-deleting) as a sane default, seems like we could also make these changes as sane defaults that you almost always want unless you really know what you're doing.  Deferring to you though b/c I'm just kinda guessing!

* `user: "<user-name>"` -> `user: medic` - line [15](https://github.com/medic/helm-charts/blob/b4616fa722ce506087daf1442ff55b6d3705e123/charts/cht-chart-4x/values.yaml#L15C3-L15C22)
* `uuid: "<uuid-value>"` -> `uuid: 1c9b420e-1847-49e9-9cdf-5350b32f6c85` - line [16](https://github.com/medic/helm-charts/blob/b4616fa722ce506087daf1442ff55b6d3705e123/charts/cht-chart-4x/values.yaml#L16C3-L16C34)
* `certificate: "arn:aws:iam::<account-id>:server-certificate/2023-wildcard-dev-medicmobile-org-chain"` -> `certificate: "arn:aws:iam::720541322708:server-certificate/2023-wildcard-dev-medicmobile-org-chain"` - line [30](https://github.com/medic/helm-charts/blob/b4616fa722ce506087daf1442ff55b6d3705e123/charts/cht-chart-4x/values.yaml#L30C5-L30C104) (does account ID ever change?)
* `hosted_zone_id: "<the-hosted-zone-id>"` -> `hosted_zone_id: "Z3304WUAJTCM7P"` - line [34](https://github.com/medic/helm-charts/blob/b4616fa722ce506087daf1442ff55b6d3705e123/charts/cht-chart-4x/values.yaml#L34C3-L34C41) (does zone ever change?)
* `node-1: "gamma-cht-couchdb-1` -> `node-1: "<your-project-name>-cht-couchdb-1` - line [46](https://github.com/medic/helm-charts/blob/b4616fa722ce506087daf1442ff55b6d3705e123/charts/cht-chart-4x/values.yaml#L46) (same for 47 and 48)

**Comment by nydr** [comment]
> * `user: "<user-name>"` -> `user: medic` - line [15](https://github.com/medic/helm-charts/blob/b4616fa722ce506087daf1442ff55b6d3705e123/charts/cht-chart-4x/values.yaml#L15C3-L15C22)

Looks good
> * `uuid: "<uuid-value>"` -> `uuid: 1c9b420e-1847-49e9-9cdf-5350b32f6c85` - line [16](https://github.com/medic/helm-charts/blob/b4616fa722ce506087daf1442ff55b6d3705e123/charts/cht-chart-4x/values.yaml#L16C3-L16C34)

IMO this should be autogenerated see [cht-user secret.yml](https://github.com/medic/helm-charts/blob/b4616fa722ce506087daf1442ff55b6d3705e123/charts/cht-user-management/templates/_secret.tpl#L22-L29), additionally I think it should be unique for each node, and currently it looks like it sets each node in a cluster to the same which seems unintentional. Not sure about the implications of sharing uuid across a couchdb cluster. FYI @Hareet @henokgetachew @dianabarsan 
> * `certificate: "arn:aws:iam::<account-id>:server-certificate/2023-wildcard-dev-medicmobile-org-chain"` -> `certificate: "arn:aws:iam::720541322708:server-certificate/2023-wildcard-dev-medicmobile-org-chain"` - line [30](https://github.com/medic/helm-charts/blob/b4616fa722ce506087daf1442ff55b6d3705e123/charts/cht-chart-4x/values.yaml#L30C5-L30C104) (does account ID ever change?)

It is tied to medic AWS account so I would not expect it to change
> * `hosted_zone_id: "<the-hosted-zone-id>"` -> `hosted_zone_id: "Z3304WUAJTCM7P"` - line [34](https://github.com/medic/helm-charts/blob/b4616fa722ce506087daf1442ff55b6d3705e123/charts/cht-chart-4x/values.yaml#L34C3-L34C41) (does zone ever change?)

This isn't being used in the helm chart but for the cht-deploy for creating route53 dns entries, I think this logic should be removed since .dev has wildcard dns to eks dev so it is not needed and most users don't have dns edit access. Thoughts @Hareet @henokgetachew ?

> * `node-1: "gamma-cht-couchdb-1` -> `node-1: "<your-project-name>-cht-couchdb-1` - line [46](https://github.com/medic/helm-charts/blob/b4616fa722ce506087daf1442ff55b6d3705e123/charts/cht-chart-4x/values.yaml#L46) (same for 47 and 48)

This field is being made optional and default disabled in #5

**Review by nydr — APPROVED** [review]
Version in Chart.yaml should be updated, otherwise LGTM!

**Comment by mrjones-plip** [comment]
I'd expect this PR to be `0.3.0`, but it looks like others have been using patch SemVer instead of minor when I look at [the change log](https://github.com/medic/helm-charts/).

@nydr - what do you recommend?

**Comment by mrjones-plip** [comment]
noting from slack thread @garethbowen suggests:

> Because we are using this in prod (right?) I propose we bump it to 1.0.0 on the next release and then follow the semver conventions after that.

Yes, we are using in prod ;)

fixed in [aba4bd8](https://github.com/medic/helm-charts/pull/11/commits/aba4bd813ea25324bdaaf6e60a6693b38c5f3717)

**Pull request merged**
